cloudforet-io/monitoring

- src/spaceone/monitoring/conf/router_conf.py
- src/spaceone/monitoring/interface/rest/v1/alert.py
- recover prefix for monitoring event
- refactoring update_alert_state_post return value
> Recover prefix for monitoring event

- src/spaceone/monitoring/interface/rest/v1/alert.py
- change return msg for update_alert_state_post
- `{}` was missing
* #10
> Change return msg for update_alert_state_post

- src/spaceone/monitoring/interface/rest/v1/alert.py
- src/spaceone/monitoring/interface/rest/v1/event.py
- src/spaceone/monitoring/model/event_model.py
- add body class for create_event request
* #11
> Add body class for create_event request

- src/spaceone/monitoring/interface/rest/v1/event.py
- remove create_event body model
> Remove create_event body model

- src/spaceone/monitoring/info/alert_info.py
- src/spaceone/monitoring/manager/alert_manager.py
- src/spaceone/monitoring/model/__init__.py
- src/spaceone/monitoring/model/alert_model.py
- src/spaceone/monitoring/service/alert_service.py
Signed-off-by: Seolmin Kwon <seolmin@megazone.com>
apply alert_number_str field in create method of alert service
* #9
> apply alert_number_str field in create method of alert service

- src/spaceone/monitoring/conf/router_conf.py
> Modify router_conf.py

- src/spaceone/monitoring/manager/inventory_manager.py
- src/spaceone/monitoring/manager/secret_manager.py
- test/service/test_log_service.py
- test/service/test_metric_service.py
- The secret path of the cloud service has been changed.
- Fix the code to get the secret_id. (`collection_info.secrets` -> `collection_info.secret_id`)
> fix: fix change secret path of cloud service

- src/spaceone/monitoring/manager/secret_manager.py
- fix bug getting `secret_id` from `collection_info`
> fix: fix bug getting secret_id from collection_info

- src/spaceone/monitoring/service/job_service.py
Signed-off-by: seolmin <seolmin@megazone.com>
* add account field in tags when creating notification message
> add account field in tags when creating notification message

- src/spaceone/monitoring/service/job_service.py
Signed-off-by: seolmin <seolmin@megazone.com>
* modify logic to put account in tags when creating message
> modify logic to put account in tags when creating message

- src/spaceone/monitoring/model/plugin_metadata_model.py
Add supported_providers in LogPluginMetadataModel
> Add supported_providers in LogPluginMetadataModel

- src/spaceone/monitoring/manager/secret_manager.py
- src/spaceone/monitoring/service/log_service.py
- src/spaceone/monitoring/service/metric_service.py
Add to get secret from metadata.plugin_info
> Add to get secret from metadata.plugin_info

- src/spaceone/monitoring/manager/secret_manager.py
fix: modify list_secrets_from_query
> Modify list_secrets_from_query

- src/spaceone/monitoring/manager/plugin_manager.py
> etc: add LOGGER for debug

- deploy/helm/Chart.yaml
- deploy/helm/config/nginx.conf
> build: change nginx.conf

- src/spaceone/monitoring/service/log_service.py
> Add LOGGER for debug

- src/spaceone/monitoring/service/log_service.py
modify get query from cloud service
> fix: modify get query from cloud service

- src/spaceone/monitoring/manager/event_manager.py
- src/spaceone/monitoring/service/event_service.py
* Add project id field in validation of matching event
> Add project id field in validation of matching event

- src/spaceone/monitoring/service/event_service.py
* Delete transaction attr settings in EventService
> Delete transaction attr settings in EventService

- src/spaceone/monitoring/manager/identity_manager.py
- src/spaceone/monitoring/manager/notification_manager.py
|Worker|Resource|Verb|SpaceConnector|Manager|
|:---:|---|:---|:---:|:---:|
|monitoring|MaintenanceWindow|close_maintenance_window|X|X|
|monitoring|Job|create_jobs_by_domain|O|Identity, Notification|
> Change so that TOKEN can be obtained from GLOBAL when using SpaceConnector in worker

- pkg/pip_requirements.txt
> build: change require packages

- src/spaceone/monitoring/service/event_service.py
* Change the description to be updated every time the same alert occurs
> fix: change the description to be updated every time the same alert occurs

- pkg/pip_requirements.txt
- src/setup.py
* Fix spaceone-api version in monitoring service
> build: fix spaceone-api version in monitoring service

- pkg/pip_requirements.txt
* Remove library in pip_requirements.txt
> build: remove library in pip_requirements.txt

- deploy/helm/Chart.yaml
- deploy/helm/templates/deployment-rest.yaml
- deploy/helm/templates/deployment-scheduler.yaml
- deploy/helm/templates/deployment-worker.yaml
> build: reformat yaml

- deploy/helm/values.yaml
> build: remove maintenance_window method in values.yaml

- src/spaceone/monitoring/manager/data_source_plugin_manager.py
- src/spaceone/monitoring/manager/secret_manager.py
- src/spaceone/monitoring/service/alert_service.py
- src/spaceone/monitoring/service/data_source_service.py
- src/spaceone/monitoring/service/escalation_policy_service.py
- src/spaceone/monitoring/service/event_rule_service.py
- src/spaceone/monitoring/service/event_service.py
- src/spaceone/monitoring/service/job_service.py
- src/spaceone/monitoring/service/log_service.py
- src/spaceone/monitoring/service/metric_service.py
- src/spaceone/monitoring/service/note_service.py
- src/spaceone/monitoring/service/project_alert_config_service.py
- src/spaceone/monitoring/service/webhook_service.py
* Add resource name in services
> fix: add resource name in services

- src/spaceone/monitoring/manager/escalation_policy_manager.py
- src/spaceone/monitoring/service/project_alert_config_service.py
> fix: add role_type in project_alert_config service

- src/spaceone/monitoring/manager/escalation_policy_manager.py
- src/spaceone/monitoring/manager/identity_manager.py
- src/spaceone/monitoring/service/escalation_policy_service.py
- src/spaceone/monitoring/service/project_alert_config_service.py
> fix: change create method of default escalation policy

- src/spaceone/monitoring/model/alert_model.py
- add workspace_id at AlertNumber model
> Add workspace_id at AlertNumber model

- src/spaceone/monitoring/conf/global_conf.py
- src/spaceone/monitoring/manager/event_rule_manager.py
- src/spaceone/monitoring/manager/identity_manager.py
> fix: add match_service_account action in event_rule resource

- src/spaceone/monitoring/service/alert_service.py
> fix: change required key in alert service

- src/spaceone/monitoring/manager/event_manager.py
- src/spaceone/monitoring/manager/event_rule_manager.py
- src/spaceone/monitoring/service/event_rule_service.py
- test/service/test_data_source_service.py
- test/service/test_log_service.py
> fix: change sort query

- src/spaceone/monitoring/service/alert_service.py
> fix: fix get, list method in alert service

- src/setup.py
* add spaceone-core package in setup.py
> chore: add spaceone-core package in setup.py

- src/spaceone/monitoring/service/alert_service.py
- src/spaceone/monitoring/service/event_rule_service.py
> fix: add reset_description field in Alert update method

- src/spaceone/monitoring/service/project_alert_config_service.py
…onfig
- fix parameter order when get escalation policy at update alert conifg
> Fix parameter order when get escalation policy at update alert conifg

- src/spaceone/monitoring/info/event_rule_info.py
- src/spaceone/monitoring/service/event_rule_service.py
> Add workspace_id at EventRuleInfo

- src/spaceone/monitoring/service/job_service.py
> fix: add workspace_id in job service

- src/spaceone/monitoring/manager/identity_manager.py
- src/spaceone/monitoring/service/job_service.py
> fix: remove wrong domain_id in job service

- src/spaceone/monitoring/manager/identity_manager.py
- src/spaceone/monitoring/manager/notification_manager.py
- src/spaceone/monitoring/service/job_service.py
> fix: add x_domain_id when using another service by worker

- src/spaceone/monitoring/service/job_service.py
> fix: delete unusable cache in job service

- src/spaceone/monitoring/manager/notification_manager.py
- src/spaceone/monitoring/service/job_service.py
> fix: fix typo

- src/spaceone/monitoring/manager/notification_manager.py
> fix: change get token method in notification manager

- src/spaceone/monitoring/manager/project_alert_config_manager.py
- src/spaceone/monitoring/service/alert_service.py
- src/spaceone/monitoring/service/event_service.py
- src/spaceone/monitoring/service/job_service.py
- src/spaceone/monitoring/service/project_alert_config_service.py
- src/spaceone/monitoring/service/webhook_service.py
> fix: add workspace_id when using get_project_alert_config method

- src/spaceone/monitoring/manager/webhook_plugin_manager.py
> fix: change wrong method in WebhookPluginManager

- src/spaceone/monitoring/manager/identity_manager.py
- src/spaceone/monitoring/manager/notification_manager.py
- src/spaceone/monitoring/service/job_service.py
> fix: add get_domain_by_system_token method in IdentityManager

- src/spaceone/monitoring/manager/identity_manager.py
- src/spaceone/monitoring/service/job_service.py
> fix: fix get_project_name method in job service

- src/spaceone/monitoring/service/job_service.py
> fix: fix cache settings in job service

- src/spaceone/monitoring/manager/identity_manager.py
- src/spaceone/monitoring/service/job_service.py
> fix: change identity methods by using system token

- src/spaceone/monitoring/manager/note_manager.py
- src/spaceone/monitoring/service/note_service.py
> Fix Alert note delete error

- src/spaceone/monitoring/interface/grpc/alert.py
- src/spaceone/monitoring/manager/identity_manager.py
- src/spaceone/monitoring/service/alert_service.py
- src/spaceone/monitoring/service/event_service.py
> Add assign user api

- src/spaceone/monitoring/service/event_service.py
> fix: fix resolved_at

- src/spaceone/monitoring/service/log_service.py
* fix init_plugin method in log service
> fix: fix init_plugin method in log service

- src/spaceone/monitoring/manager/inventory_manager.py
- src/spaceone/monitoring/service/log_service.py
* Fix get_cloud_service method in log service
> fix: fix get_cloud_service method in log service

- src/spaceone/monitoring/manager/secret_manager.py
- src/spaceone/monitoring/service/log_service.py
- src/spaceone/monitoring/service/metric_service.py
* fix get_secret method in log service
> fix: fix get_secret method in log service

- src/spaceone/monitoring/manager/secret_manager.py
> fix: change schema to schema_id

- src/spaceone/monitoring/manager/secret_manager.py
* add debug code in log service
> chore: add debug code in log service

- src/spaceone/monitoring/manager/secret_manager.py
> fix: remove supported_schema in query

- src/spaceone/monitoring/service/metric_service.py
* add data_source_plugin_manager in metric service
> fix: add data_source_plugin_manager in metric service

- src/spaceone/monitoring/manager/inventory_manager.py
- src/spaceone/monitoring/service/metric_service.py
* fix list_cloud_services method in metric service
> fix: fix list_cloud_services method in metric service

- src/spaceone/monitoring/service/metric_service.py
* fix get_query_from_cloud_service method in metric service
> fix: fix get_query_from_cloud_service method in metric service

- src/spaceone/monitoring/service/metric_service.py
* add data_source_manager method in metric_service
> fix: add data_source_manager method in metric_service

- src/spaceone/monitoring/conf/global_conf.py
> fix: add log settings

- src/spaceone/monitoring/service/metric_service.py
> fix: change debug code

- src/spaceone/monitoring/service/metric_service.py
* apply logger settings when collecting metric
> fix: apply logger settings when collecting metric

- src/spaceone/monitoring/manager/identity_manager.py
- src/spaceone/monitoring/service/job_service.py
* change system token logic for Scheduler
> fix: change system token logic for Scheduler

- src/spaceone/monitoring/manager/notification_manager.py
* add token logic in notification manager
> fix: add token logic in notification manager

- src/spaceone/monitoring/service/project_alert_config_service.py
* Modify create method in ProjectAlertConfigService
> fix: modify create method in ProjectAlertConfigService

- src/spaceone/monitoring/manager/identity_manager.py
* Modify get_project method in identity manager
> fix: modify get_project method in identity manager

- src/spaceone/monitoring/service/alert_service.py
- src/spaceone/monitoring/service/job_service.py
* Add debug code for token logic
> chore: add debug code for token logic

- src/spaceone/monitoring/service/alert_service.py
- src/spaceone/monitoring/service/job_service.py
- src/spaceone/monitoring/service/project_alert_config_service.py
* modify get_project variables in project alert config service
> fix: modify get_project variables in project alert config service

- src/spaceone/monitoring/manager/identity_manager.py
- src/spaceone/monitoring/manager/notification_manager.py
* Apply get token type by using JWTUtil
> fix: apply get token type by using JWTUtil

- src/spaceone/monitoring/service/job_service.py
> fix: fix alert link

- src/spaceone/monitoring/interface/rest/v1/alert.py
> fix: fix redirect link

- src/spaceone/monitoring/manager/data_source_plugin_manager.py
- src/spaceone/monitoring/manager/webhook_plugin_manager.py
* Add no_token in webhook manager and data source plugin manager
> fix: add no_token in webhook manager and data source plugin manager

- pkg/pip_requirements.txt
- src/setup.py
> build: change require pakages

- src/spaceone/monitoring/model/escalation_policy_model.py
- refactor unique index in EscalationPolicy
> refactor: refactor unique index in EscalationPolicy

- src/spaceone/monitoring/manager/identity_manager.py
- src/spaceone/monitoring/manager/plugin_manager.py
- src/spaceone/monitoring/manager/secret_manager.py
- apply internal authentication
> feat: apply internal authentication

- src/spaceone/monitoring/manager/identity_manager.py
- src/spaceone/monitoring/manager/plugin_manager.py
- src/spaceone/monitoring/manager/secret_manager.py
> fix: change wrong system token

- src/spaceone/monitoring/manager/identity_manager.py
- src/spaceone/monitoring/service/job_service.py
> Fixed alert bugs related to project id and domain id showing up instead of project and domain names

- src/spaceone/monitoring/info/event_rule_info.py
- fix wrong field type in event rule info
> fix: fix wrong field type in event rule info

- src/spaceone/monitoring/manager/event_rule_manager.py
- src/spaceone/monitoring/service/event_rule_service.py
- src/spaceone/monitoring/service/event_service.py
- add `change_escalation_policy` action to EventRule
> feat: add change_escalation_policy action to EventRule

- src/spaceone/monitoring/conf/global_conf.py
> Update service description

- src/spaceone/monitoring/manager/secret_manager.py
fix: Change collection_info type array to dict.
> Change collection_info type array to dict.

- src/spaceone/monitoring/info/alert_info.py
- src/spaceone/monitoring/interface/rest/v1/alert.py
- src/spaceone/monitoring/manager/identity_manager.py
- src/spaceone/monitoring/model/alert_model.py
- src/spaceone/monitoring/service/alert_service.py
- src/spaceone/monitoring/service/job_service.py
- change callback url
- change alert url
> refactor: change callback and alert url

- src/spaceone/monitoring/service/alert_service.py
- src/spaceone/monitoring/service/job_service.py
> fix: fix alert bug

- src/spaceone/monitoring/interface/rest/v1/alert.py
- src/spaceone/monitoring/manager/__init__.py
- src/spaceone/monitoring/manager/config_manager.py
- src/spaceone/monitoring/manager/escalation_policy_manager.py
- src/spaceone/monitoring/manager/identity_manager.py
- src/spaceone/monitoring/manager/project_alert_config_manager.py
- src/spaceone/monitoring/service/alert_service.py
- src/spaceone/monitoring/service/event_service.py
- src/spaceone/monitoring/service/job_service.py
> feat: add fields to alert info

- src/spaceone/monitoring/manager/identity_manager.py
- src/spaceone/monitoring/service/job_service.py
> fix: fix permission issue

- src/spaceone/monitoring/info/webhook_info.py
- src/spaceone/monitoring/service/job_service.py
- change webhook response
- remove short message in alert notification
> Change Webhook Response

- src/spaceone/monitoring/service/event_service.py
fix: typo resource to resources at alert data.
> Typo resource to resources at alert data.

- src/spaceone/monitoring/service/job_service.py
> fix: fix notification bug
